### ISSUE TITLE
./extract.sh: line 18: [: too many arguments

### ISSUE THREAD

**Issue by srid** [katspaugh/youtube-flashcards#1]
This seems like a great idea to learn a second language. My first attempt lead to a lot of errors. I used this video: https://www.youtube.com/watch?v=13razgR8q7g

```
./extract.sh: line 18: [: too many arguments
et ainsi pouvoir nous révéler<br>et nous abandonner à l’orée de l'autre.	and to be able to reveal ourselves, <br>and give us an edge.<br>	<img src="2017-04-12-10-00__00-13-08-861.jpg">	[sound:2017-04-12-10-00__00-13-08-861_00-13-14-859.mp3]
./extract.sh: line 18: [: too many arguments
```

**Comment by katspaugh** [comment]
Good catch, thanks! It should be fixed now.

Btw, if you have Node.js installed, I encourage you to try the [`node` branch](https://github.com/katspaugh/youtube-flashcards/tree/node). It has some improvements over the bash version – for example, phrase padding.

**Comment by srid** [comment]
> Good catch, thanks! It should be fixed now.

Excellent. I've verified your fix. Thanks!

> Btw, if you have Node.js installed, I encourage you to try the node branch. It has some improvements over the bash version – for example, phrase padding.

I'll try it and open separate issues for any I come across.
