### ISSUE TITLE
Video clips

### ISSUE THREAD

**Issue by srid** [katspaugh/youtube-flashcards#2]
Hey, I just have a general question. 

What would you recommend if I also want the video clip to be played (in addition to the audio clip) during the flash card review process ?

**Comment by katspaugh** [comment]
Last time I tried, video didn't work that well in iOS Anki. In the desktop Anki, it opens an external window for the video player.

Code-wise, it should be enough to change the output mapping here: https://github.com/katspaugh/youtube-flashcards/blob/master/extract.sh#L42

```
sound="$(echo "${now}__${start}_${end}" | sed 's/[.:]/-/g').mp4"
ffmpeg -threads 4 -v 0 -n -i "$video" -ss "$start" -to "$end" "$output/$sound"
```

**Comment by srid** [comment]
Hmm, yet another pain point with Anki. Video clips in flash card would help one improve their audio comprehension as well. 

We really need a better Anki alternative.
